In [1]:
from data_preprocessing import *
from utils import *
import io
import sys
import re
import numpy as np
import pandas as pd

import plotly.express as px
import plotly.graph_objects as go

### Dataloading

In [2]:
bottleneck_070 = load_data('Bottleneck_Data', 'uo-180-070')
bottleneck_070

        ID  FRAME        X        Y        Z
0        1    219  130.771  772.562  155.467
1        1    220  132.569  758.186  155.467
2        1    221  134.659  745.493  155.467
3        1    222  134.878  734.659  155.467
4        1    223  133.482  724.252  155.467
...    ...    ...      ...      ...      ...
75330  148   1581  132.408 -572.917  163.764
75331  148   1582  133.420 -582.078  163.764
75332  148   1583  133.959 -590.682  163.764
75333  148   1584  134.090 -598.287  163.764
75334  148   1585  134.090 -605.003  163.764

[75335 rows x 5 columns]

### Data Generate

In [5]:
data_with_speed = add_speed(bottleneck_070)
data_with_speed

        ID  FRAME        X        Y     speed
0        1    219  130.771  772.562  2.318080
1        1    220  132.569  758.186  2.318080
2        1    221  134.659  745.493  2.058227
3        1    222  134.878  734.659  1.733794
4        1    223  133.482  724.252  1.680034
...    ...    ...      ...      ...       ...
75330  148   1581  132.408 -572.917  1.439601
75331  148   1582  133.420 -582.078  1.474676
75332  148   1583  133.959 -590.682  1.379339
75333  148   1584  134.090 -598.287  1.216981
75334  148   1585  134.090 -605.003  1.074560

[75335 rows x 5 columns]

In [4]:
process_data(data_with_speed)

Processed 50/1599 frames.
Processed 60/1599 frames.
Processed 70/1599 frames.
Processed 80/1599 frames.
Processed 90/1599 frames.
Processed 100/1599 frames.
Processed 110/1599 frames.
Processed 120/1599 frames.
Processed 130/1599 frames.
Processed 140/1599 frames.
Processed 150/1599 frames.
Processed 160/1599 frames.
Processed 170/1599 frames.
Processed 180/1599 frames.
Processed 190/1599 frames.
Processed 200/1599 frames.
Processed 210/1599 frames.
Processed 220/1599 frames.
Processed 230/1599 frames.
Processed 240/1599 frames.
Processed 250/1599 frames.
Processed 260/1599 frames.
Processed 270/1599 frames.
Processed 280/1599 frames.
Processed 290/1599 frames.
Processed 300/1599 frames.
Processed 310/1599 frames.
Processed 320/1599 frames.
Processed 330/1599 frames.
Processed 340/1599 frames.
Processed 350/1599 frames.
Processed 360/1599 frames.
Processed 370/1599 frames.
Processed 380/1599 frames.
Processed 390/1599 frames.
Processed 400/1599 frames.
Processed 410/1599 frames.
Processed 420/1599 frames.
Processed 430/1599 frames.
Processed 440/1599 frames.
Processed 450/1599 frames.
Processed 460/1599 frames.
Processed 470/1599 frames.
Processed 480/1599 frames.
Processed 490/1599 frames.
Processed 500/1599 frames.
Processed 510/1599 frames.
Processed 520/1599 frames.
Processed 530/1599 frames.
Processed 540/1599 frames.
Processed 550/1599 frames.
Processed 560/1599 frames.
Processed 570/1599 frames.
Processed 580/1599 frames.
Processed 590/1599 frames.
Processed 600/1599 frames.
Processed 610/1599 frames.
Processed 620/1599 frames.
Processed 630/1599 frames.
Processed 640/1599 frames.
Processed 650/1599 frames.
Processed 660/1599 frames.
Processed 670/1599 frames.
Processed 680/1599 frames.
Processed 690/1599 frames.
Processed 700/1599 frames.
Processed 710/1599 frames.
Processed 720/1599 frames.
Processed 730/1599 frames.
Processed 740/1599 frames.
Processed 750/1599 frames.
Processed 760/1599 frames.
Processed 770/1599 frames.
Processed 780/1599 frames.
Processed 790/1599 frames.
Processed 800/1599 frames.
Processed 810/1599 frames.
Processed 820/1599 frames.
Processed 830/1599 frames.
Processed 840/1599 frames.
Processed 850/1599 frames.
Processed 860/1599 frames.
Processed 870/1599 frames.
Processed 880/1599 frames.
Processed 890/1599 frames.
Processed 900/1599 frames.
Processed 910/1599 frames.
Processed 920/1599 frames.
Processed 930/1599 frames.
Processed 940/1599 frames.
Processed 950/1599 frames.
Processed 960/1599 frames.
Processed 970/1599 frames.
Processed 980/1599 frames.
Processed 990/1599 frames.
Processed 1000/1599 frames.
Processed 1010/1599 frames.
Processed 1020/1599 frames.
Processed 1030/1599 frames.
Processed 1040/1599 frames.
Processed 1050/1599 frames.
Processed 1060/1599 frames.
Processed 1070/1599 frames.
Processed 1080/1599 frames.
Processed 1090/1599 frames.
Processed 1100/1599 frames.
Processed 1110/1599 frames.
Processed 1120/1599 frames.
Processed 1130/1599 frames.
Processed 1140/1599 frames.
Processed 1150/1599 frames.
Processed 1160/1599 frames.
Processed 1170/1599 frames.
Processed 1180/1599 frames.
Processed 1190/1599 frames.
Processed 1200/1599 frames.
Processed 1210/1599 frames.
Processed 1220/1599 frames.
Processed 1230/1599 frames.
Processed 1240/1599 frames.
Processed 1250/1599 frames.
Processed 1260/1599 frames.
Processed 1270/1599 frames.
Processed 1280/1599 frames.
Processed 1290/1599 frames.
Processed 1300/1599 frames.
Processed 1310/1599 frames.
Processed 1320/1599 frames.
Processed 1330/1599 frames.
Processed 1340/1599 frames.
Processed 1350/1599 frames.
Processed 1360/1599 frames.
Processed 1370/1599 frames.
Processed 1380/1599 frames.
Processed 1390/1599 frames.
Processed 1400/1599 frames.
Processed 1410/1599 frames.
Processed 1420/1599 frames.
Processed 1430/1599 frames.
Processed 1440/1599 frames.
Processed 1450/1599 frames.
Processed 1460/1599 frames.
Processed 1470/1599 frames.
Dataset generated successfully!
The shape of the dataset (containing features and targets) is  (74461, 22) .

array([[ 3.49104364e+02, -8.02104000e+01, -2.06030000e+01, ...,
        -9.28091000e+01,  5.37675000e+02,  2.11570797e+00],
       [ 3.70771726e+02,  8.02104000e+01,  2.06030000e+01, ...,
        -1.25987000e+01,  5.58278000e+02,  2.70922551e+00],
       [ 2.91833810e+02, -2.89710000e+01, -8.78950000e+01, ...,
        -1.21780100e+02,  4.49780000e+02,  2.11951461e+00],
       ...,
       [ 1.12948519e+02, -3.20153000e+01, -3.69630000e+01, ...,
        -3.14644000e+01, -2.93599000e+02,  4.57825323e-01],
       [ 1.31160678e+02, -6.13977000e+01,  1.40370000e+01, ...,
        -9.28621000e+01, -2.79562000e+02,  2.45940350e-01],
       [ 1.65719466e+02, -6.27184000e+01,  9.72600000e+00, ...,
        -6.54961000e+01, -3.72070000e+02,  4.42451498e-01]])